# Generated by Django 4.0.5 on 2022-06-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature',
            field=models.ImageField(blank=True, null=True, upload_to='static/postimages'),
        ),
    ]
