# Generated by Django 4.0.5 on 2022-07-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_is_feature_alter_post_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(null=True),
        ),
    ]
