# Generated by Django 4.0.4 on 2022-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.ImageField(blank=True, null=True, upload_to='static/postimages'),
        ),
    ]
