# Generated by Django 4.0.5 on 2022-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
