# Generated by Django 4.0.5 on 2022-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, default='Thandar Phru', max_length=100, null=True),
        ),
    ]
