# Generated by Django 4.0.5 on 2022-07-14 06:57

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_post_is_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
