# Generated by Django 4.0.5 on 2022-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature',
            field=models.ImageField(blank=True, default='images/contactme.JPEG', null=True, upload_to='static/postimages'),
        ),
    ]
