# Generated by Django 4.0.5 on 2022-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_post_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature',
            field=models.ImageField(blank=True, default='static/postimages/contactme.JPEG', null=True, upload_to='static/postimages'),
        ),
    ]
